apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app
  labels:
    app: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: django-container
          image: your-dockerhub-username/messaging-app:latest  # CHANGE THIS
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DB
              value: "messaging_db"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: DB_HOST
              value: "mysql"        # name of MySQL service in Kubernetes
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
  ports:
    - protocol: TCP
      port: 8000        # internal cluster port
      targetPort: 8000  # Django container port
  type: ClusterIP       # internal-only service
