
name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: '3.12.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python Version
      run: python -c "import sys; print(sys.version)"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: install the code linting and formatting tool Ruff
      run: pip install ruff
    - name: lint code with ruff
      run: ruff --output-format=github --target-version=py39
    - name: check code formatting with flake8
      run: flake8 
      continue-on-error: false
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port:3306
        container port:3306
        character set server:utf8mb4
        collation server:utf8mb4_general_ci
        mysql version:latest
        mysql root password:${{secrets.MYSQL_ROOT_PASSWORD}}
        mysql database:
        mysql user:ci_user
        mysql password:${{secrets.MYSQL_CI_PASSWORD}}
    - name: Run Tests
      run: |
        python manage.py test
    - name: Test with Pytest
      run: |
        pip install pytest pytest-cov
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html